server:
  shutdown: graceful
spring:
  datasource:
    url: "jdbc:mysql://localhost/test"
    username: "root"
    password: "1111"
    hikari:
      maximum-pool-size: 20
stun4j:
  stf:
    conf-full-load-order: [bizMultiStep-flow, bizOnTop-flow]
      
    